name: Build iOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.2'  # or latest stable Xcode version

    - name: Build IPA
      run: |
        xcodebuild clean -project ChatGPTFreeApp.xcodeproj -scheme ChatGPTFreeApp -configuration Release
        xcodebuild archive -project ChatGPTFreeApp.xcodeproj -scheme ChatGPTFreeApp -archivePath $PWD/build/ChatGPTFreeApp.xcarchive
        xcodebuild -exportArchive -archivePath $PWD/build/ChatGPTFreeApp.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $PWD/build
      shell: bash

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: ChatGPTFreeApp-ipa
        path: build/ChatGPTFreeApp.ipa
